name: coverall


on:
    push:
        branches:
            - main

env:
    DEFAULT_NETWORK: localhost

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                tests:
                    - jest
                    - contracts

        steps:
            - uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

            - name: Restore yarn cache
              uses: actions/cache@v3
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              run: yarn

            - name: Build libraries
              run: yarn workspaces foreach --no-private run build

            - name: Test code
              run: yarn test:${{ matrix.tests }}:coverage

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  flag-name: run-${{ matrix.tests }}
                  path-to-lcov: ./coverage/${{ matrix.tests }}/lcov.info
                  parallel: true

    finish:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true
